SELECT TOP (1000) [Id]
      ,[Name]
      ,[Description]
      ,[StockCount]
      ,[LowStockThreshold]
      ,[Status]
      ,[CreatedAt]
      ,[UpdatedAt]
  FROM [DaymapInventory].[dbo].[Items]